name: Close Pull Requests

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Thank you for your contribution! We do all development and code changes in our [development repository](https://github.com/SparkBotDev/SparkBot-Development).  Please open a PR there."
  
